### ISSUE TITLE
Software Deployment clarification

### ISSUE THREAD

**Issue by raj-patel** [rackerlabs/rs-heat-docs#13]
In https://github.com/rackerlabs/rs-heat-docs/blob/master/generic-software-config.rst, under Resources section, can you add a line that explains when the first OS::Heat::SoftwareDeployment will be executed. For the 2nd OS::Heat::SoftwareDeployment, its explicit that it only run when the action is CREATE, UPDATE, SUSPEND, RESUME

**Comment by rs-randallburt** [comment]
Fixed.
