### ISSUE TITLE
heat_template_version not consistent within each .rst topic

### ISSUE THREAD

**Issue by masthalter** [rackerlabs/rs-heat-docs#17]
The heat_template_version is not consistent within each .rst topic:
- cloud-backup.rst: 
  Option-2: heat_template_version: 2014-10-16
  Full Example Template: heat_template_version: 2013-05-23
- cloud-database.rst
  Example template: heat_template_version: 2014-10-16
  Full template: heat_template_version: 2013-05-23
- cloud-loadbalancer.rst: no problem with heat_template_version, but suggest adding a heading at   bottom of file to introduce the "Full template" (to be consistent with the other topics)

**Comment by vikomall** [comment]
@masthalter  I addressed all the issues mentioned.

**Comment by masthalter** [comment]
Thanks Vijendar!

Mike
